### ISSUE TITLE
convert_byte_array should be Vec<i8>?

### ISSUE THREAD

**Issue by daschl** [jni-rs/jni-rs#101]
Hi,

I was wondering, since the byte java type maps to an i8, shouldn't byte array conversion return a `Vec<i8>` and not `Vec<u8>`?

**Comment by daschl** [comment]
I agree with you - but what happens if the byte areay coming from java has negative values?

Maybe better to take i8 and if the user know it is safe they can cast the slice?

**Comment by dmitry-timofeev** [comment]
> what happens if the byte areay coming from java has negative values?

I'd assume 8-bit values having the same binary representation, that is, -128=1000000 in two's complement as a Java `byte` being 10000000=128 as a Rust `i8` (or -1=11111111/`byte` == 11111111=255/`i8`)

> Maybe better to take i8 and if the user know it is safe they can cast the slice?

Would love to hear opinions from the Rust-literate people, as I am not one :-) Is it a safe and efficient (O(1)) operation?

**Comment by daschl** [comment]
I think the only way to do this cast is through unsafe/transmute without iterating through the whole thing, but if you know the data in it is fine then it should be okay.

I'm currently working on a tool that does this for you (not yet announced/released but if you want to take a look: https://github.com/roast-rs/roast/blob/master/docs/docs.adoc) so I'm trying to figure out the right mappings.

**Comment by dmitry-timofeev** [comment]
I see, thank you. I’d probably go with a list of `u8` as a default — I think that is much more common use case when the sign is not relevant (e.g., hashes, serialized data, raw strings).

The project looks cool! Is it correct that it is similar to #81, but uses Rust structs instead of Java classes with native methods as its input to auto-generate the JNI glue code (i.e., creates a Java proxy of a native object)? If you'd like to see how we use Rust JNI to solve that, here is a [Rust](https://github.com/exonum/exonum-java-binding/blob/master/exonum-java-binding-core/rust/src/storage/proof_list_index.rs) glue code for a proxy of a native object. Would be wonderful if the amount of boilerplate could be reduced.

**Comment by daschl** [comment]
Yes basically you write rust code and then using derive and with a combination of a cli tool we derive the proper stuff / do codegen to generate the FFI stubs and the java files. The CLI tool then puts it in the right spot. So all you have to do is write rust code and then consume it from java. the idea is for 0 boilerplate. I still have lots to work through, i.e. if you return results we can turn this into exceptions on the java side and so forth.

**Comment by dmitry-timofeev** [comment]
Closing for now — if any interest occurs in this feature, will revive. Thanks for reporting!

**Comment by cherryleafroad** [comment]
Well, I'll just say here, that in my API I need to return a byteArray from a `Vec<u8>`, and there's no way to convert the `Vec<u8>` to a `Vec<i8>`. It's nice that I can convert from `i8` to `u8`, but the other half is missing.

I had to use the byte-muck crate as a workaround for this limitation.
`bytemuck::cast_slice::<u8, i8>(&*bytes);`
