### ISSUE TITLE
set_byte_array_region and friends should take &mut array

### ISSUE THREAD

**Issue by daschl** [jni-rs/jni-rs#103]
Hi,

Currently, methods like `https://docs.rs/jni/0.10.1/src/jni/wrapper/jnienv.rs.html#1315` take the buffer they modify as non-mutable, but they are modifying its content. I wonder if the array to modify should be passed in as &mut? I think this also applies to all other similar methods on the env.

**Comment by dmitry-timofeev** [comment]
But they copy [_from_](https://docs.oracle.com/javase/10/docs/specs/jni/functions.html#setprimitivetypearrayregion-routines) the buffer into the Java array, don't they? Or using &mut with jbytebuffer?

**Comment by daschl** [comment]
yes, they copy into the java array - and the java array should be taken as a mutable ref, right?

**Comment by alexander-irbis** [comment]
The Rust side doesn't control the mutability of objects in JVM.

**Comment by rib** [comment]
These functions currently take the lower-level wrapper types (i.e. `jbyteArray`) which are a type alias for a `*mut` pointer.

There are no references involved with modifying the underlying buffer, the memory is accessed via pointers using `unsafe` code.

You can also think of it a bit like there is interior mutability.

NB: `mut` in Rust is sometimes a bit of a misnomer that more-often means "exclusive" and in this case there aren't enough guarantees about what's happening on the Java side of things for it to be safe to assume Rust has exclusive access to the state via mutable references (which come with very strict requirements for avoiding undefined behaviour) instead of pointers.

Hope that makes sense.

Since this issue is actually super old at this point I'm going to close it now, but please re-open if there is still an issue here that maybe hasn't been fully understood.
