### ISSUE TITLE
bump version `Sync impl for GlobalRef` 

### ISSUE THREAD

**Issue by niklasad1** [jni-rs/jni-rs#160]
Hey, could you bump the version on `crates.io`  to include https://github.com/jni-rs/jni-rs/pull/145?

Thanks

**Comment by dmitry-timofeev** [comment]
Hi, we’d love to, however, there is one open issue that we bumped into and ran out of time to resolve, as it requires some research: #148 

In short, there are some inconsistencies in the API that would be ideal to resolve, as they require some breaking changes, and unreleased patches already change same APIs. 

I currently see the following options: 
1. Resolve #148 if someone can work on it; update the docs.
2. Release as is with #148 unresolved, with inconsistencies in how methods accept/return `null` Java references.
3. :cherries:-pick the changes that don't modify that aspect and release them separately from the rest (but that is likely to involve quite some conflict resolution).

@jni-rs/developers , any thoughts?

**Comment by DarkEld3r** [comment]
It would be ideal to resolve the issue with null pointers handling and personally I prefer to handle them similarly to Java, but it probably requires some time and unfortunately I cannot volunteer right now.

I think it can be published as it is and hopefully be fixed in the next (breaking) release. We don't know when it will be, right?.. :upside_down_face:

**Comment by dmitry-timofeev** [comment]
@niklasad1 It is live, check out the changelog to see if you need to make some alterations to your code: https://github.com/jni-rs/jni-rs/releases/tag/v0.11.0
