### ISSUE TITLE
Refactor complex methods of JNIEnv

### ISSUE THREAD

**Issue by skletsun** [jni-rs/jni-rs#184]
The cyclomatic complexity of these methods is relatively high --> they should be simplified:
- call_static_method_unchecked()
- call_method_unchecked()
- get_field_unchecked()
- set_field_unchecked()
- get_static_field_unchecked()

**Comment by dmitry-timofeev** [comment]
Is _cognitive_ complexity high or _cyclomatic_ complexity high? The first is suppossed to fix some issues with the second (e.g., a switch statement/expression is easy to understand, but has high cyclomatic complexity). These methods look like switch expressions — hence do **not** bear a high _cognitive_ complexity.

**Comment by skletsun** [comment]
> Is _cognitive_ complexity high or _cyclomatic_ complexity high? The first is suppossed to fix some issues with the second (e.g., a switch statement/expression is easy to understand, but has high cyclomatic complexity). These methods look like switch expressions — hence do **not** bear a high _cognitive_ complexity.

I'm talking about what the clippy says: `error: the function has a cognitive complexity of 113`.
P.S. The discussion about CyC and CoC [is here](https://github.com/rust-lang/rust-clippy/issues/3793)

**Comment by dmitry-timofeev** [comment]
OK, that's what a tool says, but what a human would say — is it difficult to understand the things?

**Comment by felix91gr** [comment]
Hi y'all.

The current version of the tool is meant to address common patterns of cognitive complexity, but afaik was originally based on cyclomatic complexity so the results might be mixed.

That said, we're working on a better version based on a whitepaper on cognitive complexity (the discussion link has so many details, it's worth a read). And that version should hopefully reflect sort of how heavy the linted functions read to a human.

Sadly that version is not ready yet and therefore is not currently published in Clippy. You should probably take the current version as a good scoping tool, but always double checking with your human eye, as I think Dmitry is trying to say.

**Comment by dmitry-timofeev** [comment]
Hi @felix91gr , thank you for the explanation! The methods are basically switch expressions with macro calls in each of the branches. I see from the draft that macro calls are considered to increase the CoC — do I understand correctly that the reasoning behind such decision is that a macro might expand in rather complex code, which the user needs to be cautios about?

**Comment by felix91gr** [comment]
> I see from the draft that macro calls are considered to increase the CoC — do I understand correctly that the reasoning behind such decision is that a macro might expand in rather complex code, which the user needs to be cautios about?

Yes and no. They are treated the same as function calls.

When reading code, what usually happens is that macros simplify what would otherwise be a more complex block of code. But they do so by introducing abstraction - it's not a 0-cost replacement of that block of code. Since this kind of abstraction is similar to the abstraction introduced by function calls, they are scored in the same way :)

**Comment by dmitry-timofeev** [comment]
The function calls, as both the paper and the draft specify, do not seem to increase the score, do they? It seems to make sense — imagine a "wall" of sequentional code in tens of SLoC (containing nothing that increases CoC) vs just a couple of lines of function calls. The latter is less complex to understand as a single piece because it operates at a higher level of abstraction, splitting that huge operation in some logical steps. The reader then can either ignore them, or explore the ones that interest them. Such method is also likely to have fewer local variables, smaller 'definition-to-use' distance for locals (don't remember the exact name of that metric 🙂).

**Comment by felix91gr** [comment]
Does the Draft really say that? Hmm, then it might be outdated.

Anyways.

You should post your thoughts there in the discussion Issue. I'm not gonna discuss the topic here alone with you, that would be a waste of both your time and mine with all due respect :)

**Comment by rib** [comment]
I'm going to close this for now, while this seems too subjective to really act on right now.

If I look at the implementation of all of these functions I personally find them very simple to read, and maybe they have anyway changed since this issue was opened, I'm not sure.

It's certainly believable that there may be opportunities to optimize these. I could imagine reworking them to have separate APIs for different return types instead of passing the return type as an argument that is matched on - but this would be an issue about optimization and public API ergonomics and we could also write benchmarks to check what difference those changes would make.

We can re-open perhaps if others find there is a pressing need to reduce the complexity of these functions.
