### ISSUE TITLE
impl Default for JObject/JString/jobject/jstring/etc.

### ISSUE THREAD

**Issue by mattfs** [jni-rs/jni-rs#199]
There's a number of types that could benefit from having the `Default` trait. I've noted at least:

`JObject`
`JString`
`jobject`
`jstring`

... but I suspect that most of the raw/object types could safely implement this.

**Comment by DarkEld3r** [comment]
I'm a little bit confused: what default value for types like `jobject` do you have in mind? I can only think about `null`, but `Default` isn't implemented for `*const T`/`*mut T` and I think it is a good thing. Personally I like that Rust is more explicit about null pointers.

Types like `JString` or `JList` do have a meaningful default value, but they are created using `JNIEnv`, so unfortunately `Default` trait  cannot be used.

**Comment by mattfs** [comment]
I have some macro code for glueing Rust to Java (eventually would like to open-source it) that makes use of default types in the case of errors. I implemented a workaround with my own wrapper types for jobject/jstring to give them a null default.

JString/JObject/JList can still have a null default as they are tied to an environment lifetime, but nulls are universal and can be used with any lifetime (and can safely be created without an environment).

While Rust does generally support defaults on pointers, _not_ supporting them in a JNI library feels like it generates a lot of impedance mismatch when dealing with real Java code.

**Comment by DarkEld3r** [comment]
The idea of having empty (I would even say useless) objects as default value still doesn't look appealing to me, though I agree that Rust ↔ Java interactions ergonomics is important. Lets hear other opinions.

**Comment by mattfs** [comment]
Would be great to hear thoughts from others!

This might tie into some of the future thinking around what differentiates a `JObject` from a `jobject`. Do we always want a `JObject` to be "valid" (ie: non-null, valid representation of a Java object)?

**Comment by vitvakatu** [comment]
Personally I think `JObject` must be safe Rust object, so it must always be valid. At the same time, I don't mind if `jobject` will actually be unsafe sometimes. Though I don't think it's really a problem to use `null_ptr` in case you need default value in your code for any reason.

**Comment by dmitry-timofeev** [comment]
JObject seems to add a lifetime atop the jobject. Regarding `null` handling as the other (past, I think) difference, there is #148. Some functions had used to represent null as Err. That turned out to be confusing (= `null` as a valid result of a Java call represented as an error), so was changed to `null`.

> it must always be valid

@vitvakatu What exactly do you mean by 'valid'? There is nothing 'invalid' in a `null` reference to a Java object. Some Java methods accept `null`s as a perfectly valid input. Do you suggest that JObject, which supposedly represents *any* Java reference, is made non-null and hence can no longer be used to pass a valid argument to a Java method/represent a valid result?

**Comment by vitvakatu** [comment]
> There is nothing 'invalid' in a null reference to a Java object.

Well, by `valid` I considered the pointer which is not `null` and points to an object (or to a pointer which is valid). Though every Java method indeed can return `null` or accept `null` as an argument, so this idea feels less appropriate now.

**Comment by mattfs** [comment]
> Some Java methods accept nulls as a perfectly valid input. Do you suggest that JObject, which supposedly represents any Java reference, is made non-null and hence can no longer be used to pass a valid argument to a Java method/represent a valid result?

Unsure if this is the right answer, but what if nullable `JObject`s were required to be `Option<JObject>`, where JObject was a `NonNull`. Does `#[repr(transparent)]` guarantee that would be compatible with Java's semantics?

**Comment by dmitry-timofeev** [comment]
Having non-null JObject is an interesting option to consider. I can't tell all the consequences, but it would require any native Java method to either use `jobject` or `Option<JObject>` in its signature (currently either `jobject` or `JObject` is fine thanks to the latter declared with `#[repr(transparent)]`). 

One of the questions when considering the explicit representation for `null`s, I think, is how often the native code needs to handle `null`s itself  ([some caches](https://github.com/exonum/exonum-java-binding/blob/0b344d5f530666a3a8aa39faa7cb1b9a12aaab90/exonum-java-binding/core/rust/src/utils/jni_cache.rs#L46), maybe) instead of just passing that reference to some JNI/Java method. Some JNI methods would probably benefit from accepting a non-null reference (if they require non-null arguments); regarding Java methods called with `JNIEnv#call_method`/`call_static_method` we cannot make any assumptions — some arguments might or might not be nullable.

**Comment by argv-minus-one** [comment]
IMHO, the `Default` for any Java-reflecting type should be whatever the JVM spec says.

All Java types have a default value defined by the JVM specification: zero for integer types, positive zero for floating-point types, false for `boolean` ([JVMS §2.3](https://docs.oracle.com/javase/specs/jvms/se15/html/jvms-2.html#jvms-2.3)), and `null` for reference types ([JVMS §2.4](https://docs.oracle.com/javase/specs/jvms/se15/html/jvms-2.html#jvms-2.4)).

For all of the Java primitive types, the Rust equivalent has the same default as Java.

For the reference types (`JObject`, etc), there currently is no default. If you follow the JVM spec, the default for these should be `null`. These types are all nullable, and they *must* be nullable to be FFI-compatible (otherwise, getting a `null` reference from Java code causes undefined behavior instead of the `NullPointerException` that Java code would expect), so `null` is a valid value for them. Also, `null` is the only value for these types that can be created without a `JNIEnv` call, which isn't possible inside a `Default` implementation.

`JValue` doesn't represent exactly one Java type, so there probably shouldn't be a default.

`sys::jvalue` could have a default value of `std::mem::zeroed()`, but that's only valid on machines where a null pointer is all zero bits. This is the case on most machines, but not necessarily all, and it will result in undefined behavior on any machine where this isn't the case, so it's probably best to leave `sys::jvalue` without a default.

**Comment by mattfs** [comment]
> but that's only valid on machines where a null pointer is all zero bits

There could be a compile-time test to ensure that zero bits == null pointer. I am pretty sure that Rust relies on this. No reason to overcomplicate code for legacy platforms that are no longer in service.

**Comment by dmitry-timofeev** [comment]
@stanislav-tkach , as you had some concerns on implementing `Default` for `JObject`, could you please take a look into this issue? Are there any potential issues?

**Comment by stanislav-tkach** [comment]
@dmitry-timofeev
Honestly, I'm not really sure about my original argumentation now. 🙃 I think that it would be OK to have such implementations.

@argv-minus-one 
I'm not sure about `sys::jvalue`, though. Do you think this type will also benefit from having the `Default` trait implementation? Personally, I prefer to leave the `sys` types as they are.

**Comment by argv-minus-one** [comment]
@stanislav-tkach

> I'm not sure about `sys::jvalue`, though. Do you think this type will also benefit from having the `Default` trait implementation?

It could, as long as the all-zero bit pattern yields a valid null pointer. I suggest including a test with something to the effect of `assert_eq!(unsafe { jvalue::default().l }, std::ptr::null_mut(), "this platform uses non-zero null pointers")` to verify this.

> Personally, I prefer to leave the `sys` types as they are.

That's fine too. I haven't needed a default value for it so far.

**Comment by chrismooredev** [comment]
I've gone ahead and taken the 'help wanted' label as direction to submit a PR for this issue, #324 :)

This change/addition feels consistent with the existence of `JObject::null()`, meaning that `JObject`/family can be "`null`" objects, but I did not implement it for the sys::object types as I felt like stdlib's approach of them not having a 'null' default (especially for the more 'unsafe' raw pointer style) makes sense - keep the more footgun-y types more explicit where possible.

I also agree that the crate should take a more solid stance on how null types are handled. While I think it may be harder to reason about, I think `Option<JObject<'_>>` would be my preference, where `JObject` is defined as `JObject(std::ptr::NonNull<jobject>)`.

As called out earlier, I believe this would also allow native java function implementations to accept `Option<JObject>` as parameters, and return it as well.

As a side effect, it could allow more type-safety within this library as we could require that objects passed to `JNIEnv` to be non-null, as appropriate.

I'm excited to get this change published for my own personal crate, which creates type-safe bindings for Java classes for Rust. :)

**Comment by rib** [comment]
Since #324 was merged and the idea about possibly updating how jni-rs tracks null objects is currently tracked by issue #148 I think we can close this now
