### ISSUE TITLE
Question about closures callbacks

### ISSUE THREAD

**Issue by matpaul** [jni-rs/jni-rs#218]
Hello! I have a question about closure callbacks
I have a code called by java
```rust
... 
let mut x = 1;
let callback = move || {
  x = x + 1;
  let env = jvm.attach_current_thread().expect("can not attach current thread");
  ...
};
...
```

Next I pass this callback using jni

```rust
// Trait object with a stable address
let func = Box::new(callback ) as Box<dyn FnMut() -> ()>;
// Thin pointer
let func = Box::new(func);
// Raw pointer
let lparam = Box::into_raw(func);
// lparam pass to java
...
```

And on callback happen call rs function
```rust
#[no_mangle]
pub unsafe extern "C" fn Java_rs_com_rsapp_RSOnClick(
    env: JNIEnv,
    _: JClass,
    lparam: jlong,
) {
    let cb = lparam as *mut Box<dyn FnMut() -> ()>;
    (*cb)();
}
```

So everything work if my callback `move` but I need pass callback without `move` and 
like
```rust
let callback = || {
  x = x + 1;
  let env = jvm.attach_current_thread().expect("can not attach current thread");
  ...
};
```
and here we have exception "can not attach current thread: Error(JavaVMMethodNotFound("AttachCurrentThread")"

Any suggestion how to fix it
Thank you

**Comment by vitvakatu** [comment]
Hello, thank you for creating an issue!

The error message looks weird to be honest, but I don't think that `non-move` callbacks are possible in such scenario. Every callback is essentially a structure representing some execution context with `call` method.
So your `move` callback is translated into
```rust
struct Callback {
    x: i32
}
```
while your `non-move` callback is translated into
```rust
struct Callback<'a> {
    x: &'a mut i32
}
```

When you wrap callback into `Box`, the compiler can no longer verify the lifetime of the `x` variable, enclosed from the closure scope. It's getting harder even for a human to prove that your `x` will still be able at the moment of callback execution. (Actually it won't, because you're calling callback in a separated JNI function).

So I suggest you to use shared mutable state, such as `Arc<RefCell<...>>`, for passing values to the closure.

**Comment by DarkEld3r** [comment]
One more problem is that `Box<dyn Trait>` is a fat pointer and you are passing it as `jlong` which can only hold a regular pointer.

**Comment by matpaul** [comment]
Thanks you guys!

**Comment by trivigy** [comment]
@matpaul was this something you eventually were able to solve? How did you dealt with @stanislav-tkach 's comment? Looking for a reproducible working example.
