### ISSUE TITLE
Implementing JNI_OnLoad

### ISSUE THREAD

**Issue by iamchairs** [jni-rs/jni-rs#257]
Hello again.

I am trying to implement a `JNI_OnLoad` to cache some method ids. I saw this open PR here that mentions it:

https://github.com/jni-rs/jni-rs/pull/172

Specifically:

> Put together a cache of class references, populate it manually in, say, JNI_OnLoad

But I wasn't sure if that was a suggestion for that PR to expose a new feature, or something that could be done now.

Is it currently possible to provide a custom `JNI_OnLoad` method? And if so, is there any documentation/example I can use?

**Comment by dmitry-timofeev** [comment]
Hello,

It is possible and works just the same: if you expose such a function, it will get called by the JVM when the library is loaded. The documentation: https://docs.oracle.com/en/java/javase/11/docs/specs/jni/invocation.html#library-and-version-management

An example from Exonum Java: https://github.com/exonum/exonum-java-binding/blob/4e00cd8cbae198ac0e8a49cb1405092537f306bc/exonum-java-binding/core/rust/src/utils/jni_cache.rs

Note check_initialized in accessors: as we couldn't find in the spec that onload _happens-before_ any subsequent operations, it is required to perform reads of the variable `INIT` that does provide visibility guarantees.

**Comment by iamchairs** [comment]
Thank you. And that answers my second question- does this require using _unsafe_ (yes).

**Comment by ndarilek** [comment]
So to use this functionality, a function like this should be sufficient?

```rust
#[allow(non_snake_case)]
#[no_mangle]
pub extern "system" fn JNI_OnLoad(vm: JavaVM, _: *mut c_void) -> jint {
    let env = vm.get_env().expect("Cannot get reference to the JNIEnv");
    JNI_VERSION_1_8
}
```

I ask because I've been trying to confirm that it works by printing, panicking, etc. from the function, and nothing works. But maybe this function is called before the logging hooks, or before anything that might respond to `panic!`?

I'd like to make sure it's actually being called before going too far down this rabbit hole. :) Seems like it should be.

Thanks.

**Comment by dmitry-timofeev** [comment]
@ndarilek, Here's the one that definitely worked on various OpenJDK versions on major OSes (we got panicks from there :)): https://github.com/exonum/exonum-java-binding/blob/a6627aa00d10bc8175d68392e9156fbf99f48bfe/exonum-java-binding/core/rust/src/utils/jni_cache.rs#L67

**Comment by ndarilek** [comment]
In case anyone comes to this via DDG like I did, and wonders if there's any additional Rust magic needed, I'll comment with my findings:

I'm building an Android NDK app. I was using plain `NativeActivity`, but unless you're explicitly calling `System.loadLibrary(...)`, `JNI_OnLoad` isn't invoked. Note that this is in addition to loading your library via the `NativeActivity` metadata. I.e. to get `JNI_OnLoad` to run, you have to both run `System.loadLibrary(...)` *and* reference it in your activity metadata. What confused me was that everything worked without the explicit `loadLibrary` call *except* for `JNI_OnLoad`. Android's magic doesn't seem to run that for you.

Also, as suspected, `JNI_OnLoad` appears to be called before log-handling is initialized. So if you're putting `println!` in your handler to verify that it is called, or panicking, neither will put anything in android-ndk's logs. I suspected as much, but now I'm explicitly confirming it to save you some time. :)

Anyhow, seems to work now. Thanks for jni-rs. This Android JNI work is hard enough without a safe language catching the many errors I'd likely have made without it. :)

**Comment by dmitry-timofeev** [comment]
Thanks for sharing that! I haven't developed JNI libs for Android, but have found this page a very good addition to the JNI specification (its non-Android specific bits): https://developer.android.com/training/articles/perf-jni.

Do you think the section on native libraries can be clearer: https://developer.android.com/training/articles/perf-jni#native-libraries ? It seems to suggest to use `loadLibrary` on Anroid, just like in normal Java.

**Comment by ndarilek** [comment]
The specific details have faded a bit from my memory over the last couple weeks, but I'm not sure that page could be much clearer.

IIRC, the issue was that I needed to run Rust callbacks from Java interfaces. The only way I found to do this, in a way that made my Rust library easily usable in other Android projects, was to ship a Java class and a custom `NativeActivity` descendant. I don't think `NativeActivity` requires an explicit `loadLibrary` call, and looks up the library from the metadata tag. So if you go seeking docs for what I tried to do, you won't even find Google calling `loadLibrary`. If you then try calling it explicitly, and adding logging or panics, you won't see any of that trigger. Essentially this is a bit of a corner case--defining a Rust library that needs to interact with Java callbacks/interfaces--so I'm not surprised that Google's docs don't describe how to do it clearly.

Anyhow, the results are [here](https://github.com/ndarilek/tts-rs) in case any other poor soul gets stuck trying this in the future. :) Sorry I don't recall the details more clearly. I just kind of wanted to get it done, then document it as well as my fried brain could so no one has to struggle quite as much. Wasn't a jni-rs issue at all, but I imagine someone else will want to build native Rust interfaces to Android libraries at some point.

**Comment by lucaszanella** [comment]
```
use std::{os::raw::c_void, panic::catch_unwind, sync::mpsc, thread, time::Duration};
use jni::{JNIEnv, JavaVM};
use jni::objects::{GlobalRef, JClass, JObject, JString};
use jni::sys::{jbyteArray, jint, jlong, jstring, JNI_VERSION_1_6};

#[allow(non_snake_case)]
#[no_mangle]
pub extern "system" fn JNI_OnLoad(vm: JavaVM, _: *mut c_void) -> jint {
    let env = vm.get_env().expect("Cannot get reference to the JNIEnv");
    JNI_VERSION_1_6
}
```

worked for me, but I got an error with `JNI_VERSION_1_8`
