### ISSUE TITLE
how can one compare a java string by rust string?

### ISSUE THREAD

**Issue by asmmo** [jni-rs/jni-rs#312]
Assume that I have a java string as a jobject or Globalref. How to compare it to some rust string in the native code side or how to construct a rust string from the jobject or Globalref which is a java.lang.String?

**Comment by maurolacy** [comment]
In the strange land of Java, strings are UTF-16 (who knows why). Whereas Rust strings are UTF-8.

So, in the general case, you would have to convert said string to a Rust string, and do the comparison. Take a look at the `std::str::from_utf8`, and `std::str::from_utf8_unchecked` methods.

If your strings are ASCII there may be be shortcuts to that, like manually running a for loop, and doing a byte-by-byte comparison.

**Comment by TheDutchMC** [comment]
> I think that the jni-rs String-related methods automatically do this for you, but not sure about the calling semantics for your specific case.

Yup they do. you can use `JNIEnv#get_string(JObject)`.
I use it like this in my own codebases:
```rs
    /// Turn a Rust String into a JavaString
    pub fn from_rust<S: Into<JNIString>>(env: &JNIEnv<'a>, s: S) -> Result<Self> {
        let string = env.new_string(s)?;
        Ok(Self::new(Object::new(string.into(), Class::String(env)?)))
    }

    /// Turn a JavaString into a Rust String
    pub fn into_rust(&self, env: &JNIEnv<'a>) -> Result<String> {
        Ok(env.get_string(JString::from(self.0.obj))?.into())
    }
```
where Self is a tuple struct holding a wrapper around a JObject

**Comment by rib** [comment]
> In the strange land of Java (where a byte is signed and 0x80 is less than zero), strings are UTF-16 (who knows why). Whereas Rust strings are UTF-8.

It's maybe worth noting that it's even worse than this - Java uses a non-standard encoding which is like [CESU-8](https://en.wikipedia.org/wiki/CESU-8) except NUL is encoded as `C0 80` instead of zero. Also see [Modified UTF-8](https://en.wikipedia.org/wiki/UTF-8#Modified_UTF-8).

This means you can't simply use `std::str::` utilities to handle the conversion unfortunately.

Luckily `jni-rs` can handle cesu-8 string format conversions for you (based on the [cesu8](https://docs.rs/cesu8/latest/cesu8/) crate via these trait implementations: https://github.com/jni-rs/jni-rs/blob/c5592c64ab3b38cb0ac16828895934c73c50c449/src/wrapper/strings/ffi_str.rs#L53

The easiest way to let `jni-rs` handle this for you is probably via `get_string()` followed by .`into()` as in @TobiasDeBruijn's example above.

**Comment by maurolacy** [comment]
I guess it can always get worse than that. They may decide to break their already non-standard encoding again, by example. And then MM-UTF8 is born.

In the name of sanity, want to mention that I was able to read, match and process UTF-8 Java strings just fine in Rust. This was good, because it didn't require conversions / copies from Java at all (by using `from_utf8_unchecked` over a direct buffer).

After taking a look at https://en.wikipedia.org/wiki/UTF-8#Modified_UTF-8, I think it may be related to this:

_In normal usage, the language supports standard UTF-8 when reading and writing strings through [InputStreamReader](https://docs.oracle.com/javase/10/docs/api/java/io/InputStreamReader.html) and [OutputStreamWriter](https://docs.oracle.com/javase/10/docs/api/java/io/OutputStreamWriter.html) (if it is the platform's default character set or as requested by the program). However it uses Modified UTF-8 for object [serialization](https://en.wikipedia.org/wiki/Java_serialization)[[88]](https://en.wikipedia.org/wiki/UTF-8#cite_note-92) among other applications of [DataInput](https://docs.oracle.com/javase/10/docs/api/java/io/DataInput.html) and [DataOutput](https://docs.oracle.com/javase/10/docs/api/java/io/DataOutput.html), for the [Java Native Interface](https://en.wikipedia.org/wiki/Java_Native_Interface),[[89]](https://en.wikipedia.org/wiki/UTF-8#cite_note-93) and for embedding constant strings in [class files](https://en.wikipedia.org/wiki/Class_(file_format)).[[90]](https://en.wikipedia.org/wiki/UTF-8#cite_note-94)_

So, if you avoid serialising stuff using the brain dead `DataOutput` stuff (which seems to be the "recommended" way to do JNI), and already use UTF-8 in Java by default (which is possible with some trickiness) you should be fine.

**Comment by rib** [comment]
> However it uses Modified UTF-8 for object [serialization](https://en.wikipedia.org/wiki/Java_serialization)[[88]](https://en.wikipedia.org/wiki/UTF-8#cite_note-92) among other applications of [DataInput](https://docs.oracle.com/javase/10/docs/api/java/io/DataInput.html) and [DataOutput](https://docs.oracle.com/javase/10/docs/api/java/io/DataOutput.html), for the [Java Native Interface](https://en.wikipedia.org/wiki/Java_Native_Interface),[[89]](https://en.wikipedia.org/wiki/UTF-8#cite_note-93) and for embedding constant strings in [class files](https://en.wikipedia.org/wiki/Class_(file_format)).[[90]](https://en.wikipedia.org/wiki/UTF-8#cite_note-94)

Isn't the "for the Java Native Interface" part of that also warning that the JNI interface also generally us

**Comment by maurolacy** [comment]
> 
> Isn't the "for the Java Native Interface" part of that also warning that the JNI interface also generally us

Yes, of course. My point is, that the entire process is inefficient. Wouldn't be nice to have strings in a compatible format, and being able to access them directly across languages? Found a way to do that, at the expense of "some" safety, and under some conditions (i.e. using UTF-8 strings in Java already).

**Comment by rib** [comment]
okey, yeah, definitely sounds good to stick with utf8 if you can manage it

**Comment by rib** [comment]
Hopefully there was enough info in the discussion here to close this issue @asmmo - regards
