### ISSUE TITLE
How do I create a HashMap？

### ISSUE THREAD

**Issue by kekeimiku** [jni-rs/jni-rs#316]
Call Rust code from Java.
I want an example . QwQ

**Comment by maurolacy** [comment]
??? take a look at the [HashMap](https://doc.rust-lang.org/std/collections/struct.HashMap.html) documentation I guess.

**Comment by TheDutchMC** [comment]
This is how I do it:
```rs
    /// Create a Map wrapper for a new HashMap
    pub fn hashmap(env: &JNIEnv<'a>, k_class: Class<'a>, v_class: Class<'a>) -> Result<Self> {
        let hashmap = env.new_object("java/util/HashMap", "()V", &[])?;

        Ok(Self {
            inner: Object::new(hashmap, Class::HashMap(env)?),
            k_class,
            v_class
        })
    }
```

The confusing bit might be the constructor signature. Quite a bit of people expect the constructor to return an instance of the Class, so you'd expect the signature to be `()Ljava/util/HashMap`, but in reality it returns void, hence the signature `()V`, because it initializes the class, it doesn't create it. 

Hope this helps you!
