### ISSUE TITLE
JNIEnv#get_string() panics when given a non-string, rather than returning an Err

### ISSUE THREAD

**Issue by TobiasDeBruijn** [jni-rs/jni-rs#328]
As the title suggests, the get_string fn on JNIEnv panics when given an object which is not a String.

The panic seems to occur within the JVM, so I dont think that panic can be avoided, but a check could be an option.

I'm unsure if it's intented behaviour for it to panic, likely it is, since that's just a programmer's fault. Though I suppose an invalid signature is too, which doesn't panic.

Here's the code that triggered it for me, which obviously has a bug:
```rs
        let return_type = env.call_method(method, "getReturnType", "()Ljava/lang/Class;", &[])?.l()?;
        let return_type_name: String = env.get_string(return_type.into())?.into();
```
where method is an instance of `java.lang.reflect.Method`,  I should have been calling getName, rather than trying to stringify a `java.lang.Class`.

**Comment by stanislav-tkach** [comment]
I think that even if we decide against adding the check, at least the `get_string` function documentation should be updated to mention a potential panic.

**Comment by mjh316** [comment]
Is there an update on this? Tried to run through the example on docs.rs, but encountered a SIGSEV from JNIEnv#get_string (not sure if it's completely related).

**Comment by TobiasDeBruijn** [comment]
Only the docs have been updated. I think we should still add a check that checks the object passed in is of java.lang.String. we can then also add an unchecked variant (possibly unsafe?) Which developers van use to avoid the performance penalty.

**Comment by mjh316** [comment]
For the check, I was thinking we could put
```rust
match self.is_instance_of(obj, self.find_class("java/lang/String").unwrap()) {
            Ok(false) => return Err(Error::JavaException), // <- Not sure what type of Error to return
            Err(err) => return Err(err),
            _ => (),
        };
```
after the null check. Would this be sufficient?

**Comment by TobiasDeBruijn** [comment]
I think that looks OK, though does that work for classes that extend String (is that even possible, but if it is, we should allow it I'd think?), maybe we need to use something like is_assignable_from?

I think we should also have a new error type, something similar to what HTTP does with Bad Request, but then Bad Input or something?

Possible optimization: Can we put the find_class in a Once? or is that unsound due to the JNIEnv?

**Comment by rib** [comment]
Just for reference here I ended up creating these tests to see what's happening here:

```rust
#[test]
pub fn test_null_get_string() {
    let env = attach_current_thread();
    let ret = env.get_string(unsafe { JString::from_raw(std::ptr::null_mut() as _) });
    assert!(ret.is_err());
}

#[test]
pub fn test_invalid_list_get_string() {
    let env = attach_current_thread();
    let class = env.auto_local(env.find_class("java/util/List").unwrap());
    let ret = env.get_string(class.as_obj().into());
    assert!(ret.is_err());
}
```

sure enough things blow up as suggested above when trying to call `get_string` with something that isn't a `String`.

The thing I was initially confused by with this issue was that it refers to a "panic" which to me is a very specific mechanism Rust has for exiting a program but really "panic" here is more of a casual - "it blows up" / "you hit undefined behaviour".

To my mind that's more serious than a panic - essentially JNI requires the caller to check that you are passing a `String` otherwise there's no guarantee whatsoever what `GetStringUTFChars` will do.

I think the docs that were recently updated to note that this API may panic should probably be updated further to add a  `# Safety` section that notes that you can hit undefined behaviour if you call the function with anything that isn't a valid `String` or `null`.

Different JVM implementations may presumably do different things in this case.

The API as it is currently is also very `unsafe` because of the responsibility of the caller to check what is passed to it.

**Comment by TobiasDeBruijn** [comment]
That's a very good point. I suppose my change to mark it `unsafe` in #370 makes even more sense then
