### ISSUE TITLE
Inherit Java class in Rust?

### ISSUE THREAD

**Issue by Hoodad** [jni-rs/jni-rs#340]
Hello!

I like to know if there is a way to inherit a Java class from Rust preferably using jni. More specifically I’m looking to inherit Androids Activity class in order to override the [OnNewIntent](https://developer.android.com/reference/android/app/Activity.html#onNewIntent(android.content.Intent))  function. 

From my research this project seems to be the most likely place where I could possible find an answer. If this is the wrong place to ask feel free to close this issue.

All help is greatly appreciated!

**Comment by TobiasDeBruijn** [comment]
Unfortunately, it is not.

However, there are some methods (though not with only JNI):
- Write the class in Java/Kotlin, compile it, and add the class to the classpath, and instantiate it via JNI
- Use a library which can write java bytecode and use that to write the class.

Personally, I'd go with option 1 though, as it's much simpler

**Comment by rib** [comment]
Okey, I'm going to close this issue now - as @TobiasDeBruijn mentioned, it's unfortunately not something that JNI supports.

JNI only really provides a way to interact with your existing Java/Kotlin code (it mainly just provides a means to make function calls between Java and native code). JNI is not really about enabling general mutation of JVM state such as constructing subclasses.

Technically JNI could be used to load byte code as mentioned above but that may also hit [platform / JVM specific limitations](https://developer.android.com/training/articles/perf-jni#unsupported-featuresbackwards-compatibility). (Android doesn't implement `DefineClass` for instance)

In the specific case of wanting to subclass an Android `Activity` that would also be a chicken / egg problem for a native application on Android because it's the `Activity` that bootstraps a native Android application (so you'd also need a way to swap out an existing implementation of a class).
