### ISSUE TITLE
how to do garbage collection as normal

### ISSUE THREAD

**Issue by tkkcc** [jni-rs/jni-rs#353]
```rust
fn library_func() {
   let x = env.call_method(...);
}

fn user_func(){
   library_func();
   // x or something in library_func can not be release
}
```
I am writing a library with jni, and just found jni calls memory will not be released completly after rust function scope. In order to release out-of-scope memory, I have to use `with_local_frame(capacity)` in all library_func, and the capacity seems to be related to specific library_func. And in order to keep the memory usage as less as possible all the time, inner smaller scope (for example if else scope) should be in new local frame.

My question is 
1. If I use `with_local_frame(capacity)`, how to set capacity correctly. Because `env.call_method` can create local ref duration class lookup, than `let x = env.call_method(...)` can result in more than one local ref. I don't know how to set a good capacity.

1. What if I set capacity to 0 or i32::MAX.

1. Should I wrap the result of `with_local_frame` in `auto_local`.

1. How to `auto_local` a `JList`.

1. Is there any better way to do garbage collection.

**Comment by tkkcc** [comment]
Using auto_local to wrap any new jobject seems what I what.

**Comment by rib** [comment]
Heya,

I'll add a quick TL;DR quote copied from my comments below, just in case that's the case here:

> If you don't need to use auto_local then I would probably recommend against using it because it comes with some safety risks

(maybe check my notes for (5) first)

# 1
The capacity is meant to ensure a minimum number of references that can be created. The capacity doesn't need to be exact (and an application may be able to allocate more local references than the given capacity) but I think you'd want to pass an overestimate of the number of local references you expect to need if you know in advance that you will need to make a substantial number of references. The capacity will effectively act as a hint for the JNI implementation to pre-allocate space for those references to avoid lots of repeated allocations as more and more references are created.

If you don't have a natural way of estimating this capacity then I think it's quite likely that you don't really need to use `with_local_frame`.

# 2 
The JNI [spec docs](https://docs.oracle.com/javase/8/docs/technotes/guides/jni/spec/functions.html#PushLocalFrame) for `PushLocalFrame` (used in the implementation of `with_local_frame`) don't explicitly clarify what will happen if given a capacity of zero - or a negative number.

Since the capacity will be used by the JNI implementation to pre-allocate storage for references it would probably be a bad idea to pass a large constant like `i32::MAX`. (would likely just fail with an `OutOfMemoryError`)

_As an aside; It would probably be better if `jni-rs` checked for these cases explicitly and returned an error without exposing applications to whatever the JNI implementation might do._

# 3
You usually wouldn't need to wrap the result from `with_local_frame` in an `auto_local` unless your Rust code is something like a long-running thread that is not going to return to the JVM.

# 4 
`auto_local` is used with local references to `JObject`s - which are what you would get if you made a method call from Rust to Java which returns any kind of Object.

A `JList` is a kind of utility API that caches `java/util/List` API methods for operations like adding/removing from a list.

`auto_local` wouldn't be used with a `JList` directly but it could be put around a `JObject` that you then also create a `JList` for.

E.g. something like:
```rust
{
    let list_object = env.new_object(ARRAYLIST_CLASS, "()V", &[])?;
    let auto_delete = env.auto_local(list_object);
    let list = JList::from_env(env, list_object)?;

    // local reference for list_object would be deleted here when audo_delete is dropped
}
```


# 5
The most appropriate way of handling your references generally depends on whether you:
1. have native Rust code that is mostly implementing native functions that get called from Java/JVM code
2. or else do you have long-running Rust code running in a thread that makes JNI calls.

In the first case (maybe more common)  you wouldn't _normally_ need to worry about `auto_local` or `with_local_frame` because every time your Rust code returns back to the JVM then it will effectively free your local references then.

In the later case you may need to use `auto_local` and `with_local_frame` to help manually delete local references that you create because you aren't returning control to the JVM to handle freeing those local references.

In either case you may also sometimes need to use `auto_local` and `with_local_frame` to help manually delete local references if you have code that would generate more than the maximum number of references allowed by the JNI/JVM implementation. For example if you had a long loop that called a JNI method to query some state to print which would create a local reference for each iteration of the loop. In this case it would be good to use `auto_local` inside the loop to ensure that the local references will be deleted before the next loop so that the total number of references stays low.

If you don't _need_ to use `auto_local` then I would probably recommend against using it because it comes with some safety risks if you aren't careful. Creating an `auto_local` for a JObject makes it possible for you to delete the underlying local reference while you might still have other copies of that local reference. For example:

```rust
#[allow(non_snake_case)]
#[no_mangle]
pub extern "C" fn Java_foo_Method(
    env: jni::JNIEnv,
    _class: jni::objects::JObject,
) {
   let local_ref = env.call_method(..); // call something that returns an object

   {
       let auto_delete = env.auto_local(local_ref);

       // local ref will be deleted here when auto_delete is dropped!
   }

   env.call_method(..., &[local_ref]); // this method call is passed an invalid local reference that's been deleted
}
```

In general it's maybe worth noting that it's not possible to explicitly control how garbage collection runs and there's never any guarantee that when Rust code returns to Java then the garbage collector won't always immediately free memory even if the last local reference has been released. This is just the nature of garbage collection and different JVMs may employ different garbage collection algorithms / architectures with different strategies for deciding when to free memory that's no longer referenced.

I get the impression that you're expecting the Java garbage collector to run precisely when returning from native Rust code back to Java and since you're seeing that memory isn't being freed immediately then you're worried that you're supposed to be doing something to fix this?

If you don't have a problem with creating too many local references, and if you aren't using JNI from a long-running Rust thread there's a good chance that you can avoid using `auto_local` and simply rely on local references being automatically deleted when your Rust code returns control to Java/JVM code. Memory won't always be freed for unreferenced objects when returning to Java but there's also no guarantee that `auto_local` or `with_local_frame` will affect when the GC frees memory either.


Hope some of those notes help here.

**Comment by rib** [comment]
Okey, closing this, since I think the original question / issue was hopefully addressed in the comment above.

As a heads up though, there have been some changes in 0.21 that relate to the discussion above.

Mainly from https://github.com/jni-rs/jni-rs/pull/398 and https://github.com/jni-rs/jni-rs/pull/404

`AutoLocal` is safer and more ergonomic than it used to be because it's harder to accidentally access an invalid local reference that is deleted via `AutoLocal` and `AutoLocal` no longer erases the type of reference that it wraps (so an `AutoLocal<JClass>` can deref to a `&JClass`)

`with_local_frame` no longer assumes you want to return a local reference to an object and allows you to return anything you'd like. 

Also ref: https://github.com/jni-rs/jni-rs/blob/master/docs/0.21-MIGRATION.md
