### ISSUE TITLE
How to call methods on a Rust struct from Java?

### ISSUE THREAD

**Issue by dabreegster** [jni-rs/jni-rs#394]
I've followed the [example Counter code](https://github.com/jni-rs/jni-rs/blob/f8e78e3583ce850c2699c5e72cb8517d8fff09a6/example/mylib/src/lib.rs#L100), which creates a Rust struct, returns it to Java, and then calls methods using the struct from Java. All of this works by returning a raw `long` pointer to `Counter`, which makes the API from Java extremely strange.

Here's my working code using static methods and `long` pointers in Java: https://github.com/a-b-street/osm2streets/commit/7acc25bf43ff2caab2c18b2a4cf8fdc3b72df72b

I'm trying to make a more normal Java API, so I can call methods on the `StreetNetwork` object. https://github.com/a-b-street/osm2streets/commit/90f3a760a9a630413ca3ad3d92af6fbc185cd2cc is one of my attempts, returning `jobject` instead of `jlong`. I can't get this or variations to work -- the static `create` method seems to always return null. I imagine this use case is a pretty common first one -- define a Rust struct and some methods, then be able to create that struct and call the methods from Java. If this all works end-to-end today, could we update the example code in this repo to demonstrate how?

Some possibly related resources: #327 and https://github.com/HorizenOfficial/zendoo-sc-cryptolib/blob/fe094ae7f33abc0de39052c9dd3e17d3d6f7756a/api/src/utils.rs#L56. I'm finding many other examples across Github, but I'm totally lost on how or why they work. Any help appreciated, thanks!

**Comment by rib** [comment]
On the Rust language side of things then the struct is put into a `Box` as a way to move it onto the heap and be given a stable number that addresses that struct (a pointer) which is also know to fit safely inside a Java `long` primitive value.

The JNI interface that is used to integrate native code with Java allows you to pass `long` numbers back and fourth so it's a good choice if you want to pass a reference to a native structure on the heap.

If something is passed over JNI as a Java object then that implies that there is a corresponding representation of that object within the Java Virtual Machine already. An arbitrary number that represents something else (such as a Rust `Box `pointer) is not a valid object reference for the Java virtual machine. 

You are seeing a null object because the number that you're trying to treat like an object doesn't actually exist in the Java Virtual Machine as an object and so it's basically an invalid pointer which your JVM is luckily recognizing. It's very lucky that this doesn't cause a crash instead.

If you want to send an object over to Java instead of a `long` then you could do something similar to the code you linked (https://github.com/HorizenOfficial/zendoo-sc-cryptolib/blob/fe094ae7f33abc0de39052c9dd3e17d3d6f7756a/api/src/utils.rs#L56) which is like creating a `Java` object as a wrapper for the `long` primitive (similar to creating a `Long` object instead of a `long` primitive)

You could create a custom class with a constructor that stores the primitive `long` inside, similar to that linked code.

Hope that clarifies a bit.

**Comment by dabreegster** [comment]
Thank you for the explanation! A Java object internally wrapping the raw pointer makes perfect sense to me. https://github.com/a-b-street/osm2streets/commit/3759ae4ce3ee686d1d8b44968081133ebdf1669b was quite straightforward from the example code, though I'm definitely going to go read up on the signature strings now.

Should we close this issue, or would it be useful for me to send a PR to update the example code with something like this? And should I change the existing `HelloWorld` example to follow this pattern, or start a totally fresh example?

**Comment by rib** [comment]
Great, yeah your updated code looks much better now.

It might not be a bad idea to update the Counter example to demonstrate this kind of pattern. In practice I'd guess it's probably more common to want to do something like this.

I think the example still needs to have a Java method for explicitly destroying the internal native state (which seems to be missing from your current osm2streets code (otherwise the native allocations in the Rust will be leaked).

Unfortunately there's not really a way for those native allocations to be freed automatically (I wouldn't recommend relying on a Java destructor to call a native method for freeing Rust state).

I'll close this issue for now but please feel free to open PR to update the example if you get a chance to look at that, thanks.
