### ISSUE TITLE
All APIs like `env.new_*_array()` should return a `JObject` wrapper (like `JByteArray`) allowing safe JValue conversion

### ISSUE THREAD

**Issue by EliseChouleur** [jni-rs/jni-rs#396]
Particulary to be able to call a methode with a byte array in parameter.
It was possible in JNI 0.19 thanks to `into` but the new conversion methode doesn't work with jbyteArray.

e.g:
jni-rs 0.19

```
    let buffer = env.new_byte_array(asset_size)?; 
    env.call_method(asset_stream, "read", "([B)I", &[buffer.into()])?;
```

**Comment by rib** [comment]
Ah, right, I guess this was affected when addressing the soundness issues with allowing safe conversions from sys types: https://github.com/jni-rs/jni-rs/issues/197

The odd thing here is that `jni-rs` is directly returning a sys type from `env.new_byte_array` instead of a type like `JObject` that has an associated lifetime for the local reference.

We should also track this in the context of https://github.com/jni-rs/jni-rs/issues/392 where we're looking to ensure that local reference types are non-Copy.

Since the array is effectively just an object you can pass your array to method calls like this for now:

```rust
    let buffer = env.new_byte_array(asset_size)?;
    let buffer_obj = unsafe { JObject::from_raw(buffer) };
    env.call_method(stream, "read", "([B)I", &[buffer_obj.into()])?;
```

We probably shouldn't directly allow safe conversion between `jbyteArray` and `JValue` - similar to not allowing safe conversions of `jobject` to `JObject` otherwise safe code can can easily pass literal numbers as an invalid pointers.

What we probably need to do here is introduce a `JByteArray<'env>` type similar to `JString` or `JClass` that would be returned by `env.new_byte_array()` and then there should be a safe way to convert a `JByteArray` into a `JValue` (which should make your original code work again)

**Comment by EliseChouleur** [comment]
Hello
Thanks for the temporary fix !
