### ISSUE TITLE
Report error when run HelloWord on jdk11?

### ISSUE THREAD

**Issue by lfygh** [jni-rs/jni-rs#397]
$ java --version
openjdk 11.0.15 2022-04-19 LTS
OpenJDK Runtime Environment Zulu11.56+19-CA (build 11.0.15+10-LTS)
OpenJDK 64-Bit Server VM Zulu11.56+19-CA (build 11.0.15+10-LTS, mixed mode)

$ uname -a
Darwin MacBook-Pro.local 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:31 PDT 2021; root:xnu-7195.121.3~9/RELEASE_ARM64_T8101 arm64

```
javac HelloWorld.java && java -Djava.library.path=mylib/target/debug/ HelloWorld
Exception in thread "main" java.lang.UnsatisfiedLinkError: no mylib in java.library.path: [mylib/target/debug/]
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2673)
        at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
        at java.base/java.lang.System.loadLibrary(System.java:1873)
        at HelloWorld.<clinit>(HelloWorld.java:13)

```

**Comment by rib** [comment]
Since I was also in the middle of another PR which I realize also affects this example I've just made a patch to update `example/mylib` as part of this PR: https://github.com/jni-rs/jni-rs/pull/400

You can also fetch this branch: https://github.com/rib/jni-rs/tree/array-wrapper-types

It'd be good to know if you can run the example via `cd example && make java_run` with the above branch.

**Comment by rib** [comment]
Since merging #400 then the `example/mylib` crate should compile now, so it should hopefully be possible to run `cd example && make java_run` with the current `master` branch.

I'm going to close this now that I think that the `mylib` crate builds since I think the original issue was that the `libmylib.so` hadn't been compiled prior to running `javac HelloWorld.java && java -Djava.library.path=mylib/target/debug/ HelloWorld`
