### ISSUE TITLE
Invocation API uses wrong encoding for options

### ISSUE THREAD

**Issue by kb-1000** [jni-rs/jni-rs#410]
The JVM Invocation API requires options to be in the platform default encoding, while Rust's CString always uses UTF-8 as far as I can tell (unless the code is really non-obvious). While this is (usually) correct on Linux and macOS, it isn't at all on Windows.
`local_encoding_ng` might help here.

**Comment by rib** [comment]
Ah, yep that looks like a good point!

My initial guess is that we could use [OsString](https://doc.rust-lang.org/std/ffi/struct.OsString.html) here, though the JNI spec's wording of "default platform encoding" is of course pretty vague.

Like you suggest, it looks like `InitArgsBuilder::build()` shouldn't simply create a `CString` and I guess it could instead create an `OsString` and collect that into a byte array via `OsStrExt::as_bytes`.

**Comment by kb-1000** [comment]
On windows, the platform encoding is the current codepage, the same thing functions like the C `fopen` or the "multibyte" (A) variants of win32 API functions use, which https://docs.rs/local-encoding-ng/latest/local_encoding_ng/enum.Encoding.html#variant.ANSI supports (that's why I mentioned it). That unfortunately also means you (usually) aren't getting full unicode - but right now it means you're getting nothing beyond ASCII which isn't any better.

`OsString` uses UTF-16 on Windows, which isn't correct here either. Rust uses the unicode variants of the APIs like it should, but Java unfortunately doesn't... am curious why no one made a JEP or something close for adding an unicode variant on Windows yet, but I don't think I have any control over that.

**Comment by argv-minus-one** [comment]
I'll look into this.

The solution is actually fairly simple on Windows: convert the string to UTF-16 using `std::os::windows::ffi::OsStrExt::encode_wide`, then call Win32 `WideCharToMultiByte` with `CP_ACP` to convert the string to the encoding that the JVM wants.

POSIX platforms like Linux are in a much worse situation. While it's true that they all default to UTF-8 these days (thank goodness), that's only a default and it can be changed. [POSIX doesn't even require the character encoding to be ASCII-compatible](https://pubs.opengroup.org/onlinepubs/009695399/basedefs/xbd_chap06.html), let alone require it to be UTF-8.

POSIX does offer an API for discovering which character encoding is default ([`nl_langinfo(CODESET)`](https://man7.org/linux/man-pages/man3/nl_langinfo.3.html)) and converting to it from UTF-8 ([`iconv`](https://man7.org/linux/man-pages/man3/iconv.3.html)), but these functions suffer from the same environment variable race condition as https://github.com/time-rs/time/issues/293 / [CVE-2020-26235](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-26235), so using them from a library like jni-rs isn't safe. But then again, [Java itself calls thread-unsafe locale-related functions](https://github.com/openjdk/jdk/blob/960c3931337b314417ad33d8a775ee3e251692d7/src/java.base/unix/native/libjava/java_props_md.c#L106) and also [reads from `environ`](https://github.com/openjdk/jdk/blob/960c3931337b314417ad33d8a775ee3e251692d7/src/java.base/unix/native/libjava/ProcessEnvironment_md.c), so this is a moot point because starting the JVM is thread-unsafe anyway. What a mess.

I wonder if we should make `JavaVM::{new,with_libjvm}` (and now `InitArgsBuilder::new`) `unsafe` and explain that they must not be called if `cfg(unix)`, the calling process has more than one thread, and environment variables and/or the process locale might be changed on another thread.

**Comment by kb-1000** [comment]
> POSIX platforms like Linux are in a much worse situation. While it's true that they all default to UTF-8 these days (thank goodness), that's only a default and it can be changed. [POSIX doesn't even require the character encoding to be ASCII-compatible](https://pubs.opengroup.org/onlinepubs/009695399/basedefs/xbd_chap06.html), let alone require it to be UTF-8.

Given Rust itself makes the assumption of UTF-8 by for example making OsString always UTF-8 on non-Windows, I think that's a fair assumption to do.

**Comment by rib** [comment]
hmmm, looking into this a bit more I think perhaps too much is being assumed about what is meant by "default platform encoding".

This is completely unspecified in the JNI spec but if I look at the source for hotspot here: https://github.com/openjdk-mirror/jdk7u-hotspot/blob/master/src/share/vm/runtime/arguments.cpp#L107

it generally just uses strncmp for most of its option parsing, which will simply do byte-wise comparisons between options and C++ string literals that will have been encoded when the JVM itself was compiled (i.e. it doesn't care runtime locales and such, it just assumes the C lang encoding of strings)

This seems to imply options would have to have an ascii compatible encoding at least for the option names themselves - though, I'm not clear atm how it would deal with paths being specified as part of an option.

**Comment by rib** [comment]
Also seeing this issue: https://bugs.openjdk.org/browse/JDK-4488646 I tend to think that these options are simply limited to being ascii compatible (at least for hotspot).

I half expect that utf8 encoding of non-ascii characters (eg. for class.path options) would be ok but since Windows isn't utf8 based then my impression is that options are simply limited to ascii on Windows.

**Comment by rib** [comment]
So perhaps more through luck than judgement the current implementation _might_ actually make sense to keep as-is - though perhaps with some added comments.

@kb-1000 did you observe a specific bug related to this, or were you perhaps just surprised to see that the code didn't seem to be taking into account what the "default platform encoding" might be while processing options, and that looked suspect?

**Comment by kb-1000** [comment]
I had implemented something based on libjli to start a regular Java main class, which required me to deal with encoding stuff too.
As the JRE home detection logic of libjli is broken on Java 8 and below if you aren't running from within the JRE, I decided to make a second revision of the code based on regular JNI APIs, and after experimenting with making thin unsafe bindings myself found and decided to use this library (or rather the git version of it since there's no new release yet)

So when it got to options I decided to check what encoding stuff you are using for options, only to find that it's none at all.
meaning, no, it hasn't caused any concrete bugs yet, but would have had I not checked. System properties specified on the command line might need to contain non-ascii chars for example when the user uses non-ascii chars in the relevant paths or even the username (seen far too many obscure issues with encodings not being properly handled breaking such paths...).
On Windows, those are encoded using the current codepage.
Even though I can try telling windows to use an utf-8 "codepage" for my program (there's an assembly manifest element for that), which would probably cover most of it already, that was only introduced fairly recently so there's still too many users who wouldn't be helped by that. Local codepages aren't full unicode of course, but not limited to ASCII either, and any special chars the user is using in their username or paths will almost definitely be part of their local codepage.

**Comment by argv-minus-one** [comment]
Note that system properties can be set to arbitrary strings from the command line. For example, if you run:

```sh
java -Dmood=😎 -XshowSettings:properties -version
```

On Linux with a UTF-8 locale, you'll find this among the output:

```
    mood = 😎
```

It will also silently replace invalid UTF-8 sequences with U+FFFD (replacement character):

```
$ jshell -R-Dmood=$(printf '\xa0')
|  Welcome to JShell -- Version 17.0.5
|  For an introduction type: /help intro

jshell> System.getProperty("mood")
$1 ==> "�"

jshell> (int) $1.charAt(0)
$2 ==> 65533
```

It works the same way on Windows, except that characters are limited to the default code page, and yes, that includes non-ASCII characters:

```
C:\>jshell -R-Dtrademark=™
|  Welcome to JShell -- Version 17
|  For an introduction type: /help intro

jshell> System.getProperty("trademark")
$1 ==> "?"

jshell> (int) $1.charAt(0)
$2 ==> 8482
```

Back on Linux, if you change the locale to use an 8-bit character encoding but input UTF-8, then you get a Java string containing [mojibake](https://en.wikipedia.org/wiki/Mojibake):

```
$ LANG=en_US.ISO-8859-1 jshell -R-Dmood=😎
|  Welcome to JShell -- Version 17.0.5
|  For an introduction type: /help intro

jshell> System.getProperty("mood")
$1 ==> "�\237\230\216"
```

That matches the UTF-8 encoding of that emoji:

```
$ unicode 😎
U+1F60E SMILING FACE WITH SUNGLASSES
UTF-8: f0 9f 98 8e UTF-16BE: d83dde0e Decimal: &#128526; Octal: \0373016
😎Category: So (Symbol, Other); East Asian width: W (wide)
Unicode block: 1F600..1F64F; Emoticons
Bidi: ON (Other Neutrals)

$ printf '%o %o %o %o\n' 0xf0 0x9f 0x98 0x8e
360 237 230 216
```

So no, Java is definitely paying attention to the platform default character encoding, and neither assumes nor is limited to ASCII.

Obviously this is a contrived example, but yeah, this will cause real-world breakage if a file path containing non-ASCII characters is passed to the JVM as a system property. We should properly fix this. I'll see what I can do.

**Comment by rib** [comment]
Btw, just to be clear, when I say "ascii compatible" that includes utf8, so I was expecting full unicode support on POSIX should Just Work.

By "ascii compatible" I mean the encoding has to be only 1 byte per character for ascii characters, and then unicode characters can potentially be multi byte. That pretty much implies either ascii or utf8.

**Comment by argv-minus-one** [comment]
> We have very little to go on from the spec but we have some additional clues as to what's appropriate:
> 
> 1. JNI is C API, and it would be fair to expect that the API would accept C string literals (including having NUL termination)
> 
> 2. The hotspot implementation clearly compares option prefixes with C++ string literals and uses APIs like strncmp that work based on bytes and have no awareness of locales: https://github.com/openjdk-mirror/jdk7u-hotspot/blob/master/src/share/vm/runtime/arguments.cpp#L107
> 
> 
> I think we need to be careful to not read too much into what "default platform encoding" implies.
> 
> E.g. with no other context I would expect on Windows that "default platform encoding" would mean UTF-16 encoding but that is definitely not the case here because C/C++ strings aren't UTF-16 and we can see from the hotspot code that that encoding wouldn't work.
> 
> UTF-8 is pretty much the only multi-byte encoding that I can see would enable unicode support in a way that's backwards compatible with JNI's roots of being a C API that accepts string literals as well as being compatible with the code in hotspot.
> 
> Since it's still not common place to use UTF8 for everything on Windows but the encoding has to be compatible with C strings / ascii then ascii is pretty much the only thing you can rely on. (please read the next section before reacting because I didn't mention code pages here ;-p)
> 
> I would probably interpret the requirement as being more like "the C compiler's platform default encoding for C strings".

Since JNI is underspecified in this area, we can use HotSpot as our “standard”. [Here's a test](https://github.com/argv-minus-one/jni-rs/blob/invocation-character-encoding/tests/invocation_character_encoding.rs) that tries to pass a non-Unicode character through a JVM option and checks that it made it through correctly.

On Linux configured for UTF-8, this test passes:

```
$ LANG=en_US.UTF-8 cargo test --features invocation --test invocation_character_encoding
    Finished test [unoptimized + debuginfo] target(s) in 0.02s
     Running tests/invocation_character_encoding.rs (target/debug/deps/invocation_character_encoding-32acfc4febf5ea63)

running 1 test
test invocation_character_encoding ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.09s
```

On Linux configured for ISO-8859-1, this test fails:

```
$ LANG=en_US.ISO-8859-1 cargo test --features invocation --test invocation_character_encoding
    Finished test [unoptimized + debuginfo] target(s) in 0.02s
     Running tests/invocation_character_encoding.rs (target/debug/deps/invocation_character_encoding-32acfc4febf5ea63)

running 1 test
test invocation_character_encoding ... FAILED

failures:

---- invocation_character_encoding stdout ----
thread 'invocation_character_encoding' panicked at 'assertion failed: `(left == right)`
  left: `"\u{a0}"`,
 right: `"Â\u{a0}"`', tests/invocation_character_encoding.rs:42:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    invocation_character_encoding

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.13s

error: test failed, to rerun pass `--test invocation_character_encoding`
```

On Windows, it fails in the same way:

```
>cargo test --features invocation --test invocation_character_encoding
    Finished test [unoptimized + debuginfo] target(s) in 0.08s
     Running tests\invocation_character_encoding.rs (target\debug\deps\invocation_character_encoding-37cfbec49c5ee011.exe)

running 1 test
test invocation_character_encoding ... FAILED

failures:

---- invocation_character_encoding stdout ----
thread 'invocation_character_encoding' panicked at 'assertion failed: `(left == right)`
  left: `"\u{a0}"`,
 right: `"Â\u{a0}"`', tests\invocation_character_encoding.rs:42:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    invocation_character_encoding

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.07s

error: test failed, to rerun pass `--test invocation_character_encoding`
```

As you can see, HotSpot expects strings to be in the character encoding appropriate for the locale on Linux, or the default code page on Windows, which in this case is ISO-8859-1 and Windows-1252 respectively. Trying to feed it UTF-8 results in a garbled string (mojibake) unless it's all ASCII or the locale/code page indicates UTF-8, and this particular mojibake is indeed what you get when you interpret U+00A0 in UTF-8 as ISO-8859-1/Windows-1252.

> On Linux, the fact that paths are almost certainly utf8 encoded is actually not something the JVM needs to know or care about necessarily (and as far as I can tell in the hotspot code it doesn't assume or care). POSIX paths don't have a defined encoding - they are just a sequence of bytes. This matches up nicely with how JNI option values can be any NUL-safe sequence of bytes. For example on Linux if you specify a path for the JVM to find system libraries then the bytes for the path can simply be concatenated into the value of the `LD_LIBRARY_PATH` environment variable. The implementation doesn't need to check what your locale is because it has no effect on how a sequence of bytes will be interpreted as a path.

You're right that HotSpot doesn't care all that much, but the `java.io` package definitely does:

```
$ printf 'bogus_utf8_\xa0' | xargs touch
$ jshell -R-Dfile=$(ls -1 bogus_utf8_*)
|  Welcome to JShell -- Version 17.0.5
|  For an introduction type: /help intro

jshell> System.getProperty("file")
$1 ==> "bogus_utf8_�"

jshell> new java.io.FileInputStream($1)
|  Exception java.io.FileNotFoundException: bogus_utf8_� (No such file or directory)
|        at FileInputStream.open0 (Native Method)
|        at FileInputStream.open (FileInputStream.java:216)
|        at FileInputStream.<init> (FileInputStream.java:157)
|        at FileInputStream.<init> (FileInputStream.java:111)
|        at (#2:1)
```

That said, this is unavoidable, because `java.io` expects all file paths to be validly encoded in whatever character encoding it considers the default. It can't handle paths that don't fit this expectation:

```
jshell> new java.io.File(".").listFiles()[0]
$3 ==> ./bogus_utf8_�

jshell> new java.io.FileInputStream($3)
|  Exception java.io.FileNotFoundException: ./bogus_utf8_� (No such file or directory)
|        at FileInputStream.open0 (Native Method)
|        at FileInputStream.open (FileInputStream.java:216)
|        at FileInputStream.<init> (FileInputStream.java:157)
|        at (#4:1)
```

I actually had to deal with this in my other project, which has to pass file paths between Rust and Java. To make completely sure that the file path doesn't get mangled if it isn't valid in the expected encoding, it uses the url crate on the Rust side to turn a path into a URL, and then the Java side constructs a `java.nio.file.Path` from that URL. This works because URLs *can* represent invalid UTF-8, and `java.nio.file.Path`, unlike `java.io.File`, can handle such paths.

Still, people are going to expect that passing system properties and other options through `InitArgsBuilder` works the same way as with the `java` command, so we really should encode those options as HotSpot expects them.

> Is there a comprehensive, well tested, Rust crate for dealing with Windows 8-bit encoding though? - it's just not something that many things would have to care about these days and with a quick search I at least didn't find much. The [local-encoding-ng](https://crates.io/crates/local-encoding-ng) only looks like it handles two code pages (mainly just Windows-1251 which only really covers cyrillic languages)

local-encoding-ng is specifically for converting between UTF-{8,16} and whatever the Windows default code page is. It's a fairly trivial wrapper around Win32 `WideCharToMultiByte`, which can handle *any* code page supported by Windows. We can also do the same thing ourselves with the winapi or windows crate (local-encoding-ng uses winapi).

One reason we might not want to use local-encoding-ng is that its license is different from ours: it's MIT only, whereas our license is MIT/Apache2.

local-encoding-ng has a POSIX module, by the way, but it's incorrect as it assumes UTF-8. Correct handling of local encoding on POSIX systems is with `nl_langinfo` and `iconv`. [There's a crate for that](https://crates.io/crates/iconv), but it has the same licensing issue as local-encoding-ng. Using `nl_langinfo` and `iconv` through the libc crate shouldn't be overly difficult, though; I'll try that after I deal with Windows.

> I can see how it could be beneficial to look at supporting some character encoding on Windows to make up for the limitation of 8-bit encoding strings but I also mainly see this as a "it would be nice to support this" issue, certainly not a safety issue / bug of any kind.

You're right that it's not a safety issue—the JVM will happily accept garbled strings and pass them through without causing any undefined behavior—but it is a bug in that it's our library that's garbling the strings by not encoding them as the JVM expects.

> I think it's fair to keep in perspective how huge the gulf is between full unicode support and being able to squeeze in an additional ~127 characters via legacy 8-bit character encoding standards, so we can consider how much effort it makes sense to expend on supporting this. (With or without this there are significant limitations on what paths can be specified on Windows).

It's not just that. The bigger problem I see here is that not only are non-ASCII characters not currently supported, they're supported *wrong,* meaning they become garbled if used. If we simply returned an error if any non-ASCII characters are present in an option string, that would be one thing, but what we're actually doing is worse than that.

> This looks like a Windows-specific issue to me - I don't currently see any issue here for POSIX systems.

As you can see from my test results above, that is not correct. It is also an issue on POSIX systems configured to encode strings as anything other than UTF-8, which they absolutely can be.

---

Now that my test is written and we've established how HotSpot decodes option strings, I will work on getting the strings encoded like it wants.

**Comment by kb-1000** [comment]
Would be neat if whatever you'll end up with could be reused by me in that other code version using libjli... but that's just wishful thinking probably

**Comment by argv-minus-one** [comment]
I've posted PR #414, which adds code to transcode strings properly on Windows. Next I will look into doing the same for POSIX platforms.

**Comment by rib** [comment]
I agree that it's good to try and do additional character encoding/mapping on Windows to make up for the limited 8-bit byte encoding that is a real-world problem that means we can enable support for more paths with non-ascii characters.

Where I think we aren't really in agreement though is with POSIX...

It's _technically_ true that if you enable a legacy locale for something like latin-1 that involves character mapping then you can see that hotspot will transcode based on the locale but I strongly believe that we should not be adding any code or complexity in 2023 to a Rust-based project for non-utf8 locales on POSIX.

Linux distros have long since stopped generating non-utf8 locales, and I'm quite sure you would have taken additional steps to first generate an ISO-8859 locale to even run the test above. UTF8 has been widely adopted for over a decade, especially on POSIX systems.

Any code added to support non utf8 locales on POSIX is just code that we can be all but certain won't be used by anyone, which is usually a pretty clear sign that it's a bad idea.

There's really no reason in 2023 for any POSIX system to not use a utf8 based locale.

If for some esoteric reason some system happens to enable a non-UTF8 locale It's a reasonable trade off in this context that JNI options would be limited to only ascii characters. If someone really cares / needs to support non-ascii characters they have an easy, good solution which is to use utf8. Such a system would have a huge myriad of compatibility issues and a limitation to ascii paths in `jni-rs` will be the absolute least of their concerns.

Please consider how the rust standard library also has no built-in support for legacy POSIX locales and consider what the realistic chances are that anyone would have a system using a legacy locale _and_ be running anything based on Rust / `jni-rs` would be. I honestly can't imagine there is anyone in that intersection.

I think I'd even be happier seeing an explicit panic in this case than adding code / complexity / character maps in support of legacy 8-bit encodings that can be reasonably considered a foot note in history at this point in time.

It's perhaps also notable that the effort to support those character mappings for POSIX would be less beneficial than it is on Windows from the pov that POSIX paths aren't unicode aware. When you temporarily switched your system to use an ISO-8859 locale, then any files with non-ascii characters in your filesystem are still going to be utf8 encoded and even for a file with non-ascii characters where the same characters can be expressed via utf8 and e.g. latin-1 you won't be able to open those (which isn't quite the same situation as on Windows).

The same can't be said about Windows here because utf8 still isn't pervasive unfortunately - so I do agree that it's fair / worthwhile trying to have some character mapping on Windows.

**Comment by argv-minus-one** [comment]
OK, I'll leave POSIX assuming UTF-8 like it does now.
