### ISSUE TITLE
`get_rust_field()` exclusive access to `JNIEnv`

### ISSUE THREAD

**Issue by koutheir** [jni-rs/jni-rs#455]
[`get_rust_field()`](https://docs.rs/jni/latest/jni/struct.JNIEnv.html#method.get_rust_field) takes `&mut self`, giving it exclusive access to the JNI environment, thus preventing any use of that environment until the Rust value binding is dropped.

Given that `JNIEnv` only requires shared access (takes `&self`) to call most JNI methods, wouldn't it make sense to also take a shared reference in `get_rust_field()`? This would allow calling other JNI methods while still holding a binding to the Rust value.

**Comment by rib** [comment]
Yeah, the challenge here is that the general rule is that we have to take a mutable reference on the env if the operation will need to make any local references.

`get_rust_field` calls `get_field` internally which creates local references.

Requiring the mutable reference is how we make sure that you can only associate the lifetime of a local reference with the current JNI local stack frame.

This relates to how APIS like `with_local_frame` work, because they let you create a new JNI stack frame for local references and the closure can still see the env for the outer frame, as well as a new (mutable) env with a lifetime associated with the new local frame.

Code that uses `with_local_frame` can't be allowed to associate new local references with the environment for an outer JNI stack frame because that would associate them with the wrong Rust lifetime.

I suppose since the implementation only creates transient, internal local references we might be able to relax the restriction here but probably need to be careful about how we would do that.

**Comment by koutheir** [comment]
> I suppose since the implementation only creates transient, internal local references we might be able to relax the restriction here but probably need to be careful about how we would do that.

We can create a new method `get_rust_field2(&self,...)` that requires the caller to perform the resolution of the `jclass` and `jfieldID` and provide those as parameters, so that the return value of `get_rust_field2` keeps a shared reference to `JNIEnv`, instead of an exclusive reference. Does that seem reasonable?

**Comment by rib** [comment]
Technically I think it should be safe to avoid needing a separate API but it's a bit awkward.

It's awkward with how the implementation is based on `get_field` which (generally speaking) could also return a local reference, in addition to creating a temporary local reference for the `get_object_class()`.

The `AutoLocal` should be OK because we're guaranteeing that the local reference is explicitly deleted before returning.

The fact that we pass "J" to `get_field`  to query a `jlong` value also means we know that we aren't getting returned a local reference for the field.

For internal special cases like this we can use `unsafe_clone()` to effectively get a mutable `JNIEnv` we can use internally, so long as we can guarantee that we don't create any local references, or if we do we make sure they are deleted before returning to the caller.

Actually looking at the implementation details here I've just realized that `get_object_class` should take a `&mut self` but it doesn't. 

@argv-minus-one I wonder if I'm overlooking something here but would you agree that `get_object_class` should be updated to take a `&mut` reference, since it returns a `'local` reference.

**Comment by koutheir** [comment]
The following is an initial draft to discuss. If it makes sense, then I can integrate it into the project and create a pull request.

```rust
pub struct SomeStruct;

impl SomeStruct {
    unsafe fn get_jlong_field_id<'a, S>(
        env: &JNIEnv<'a>,
        class: &JClass<'a>,
        field: S,
    ) -> Result<JFieldID>
    where
        S: Into<JNIString>,
    {
        let field = field.into();

        let field_id = unsafe {
            (**env.get_raw()).GetFieldID.unwrap()(
                env.get_raw(),
                class.as_raw(),
                field.as_ptr(),
                b"J\0".as_ptr().cast(),
            )
        };

        if env.exception_check()? {
            Err(Error::JavaException)
        } else if field_id.is_null() {
            Err(Error::FieldNotFound {
                name: field.into(),
                sig: "J".into(),
            })
        } else {
            Ok(JFieldID::from_raw(field_id))
        }
    }

    unsafe fn get_jlong_field<'a>(
        env: &JNIEnv<'a>,
        obj: &JObject<'a>,
        field_id: &JFieldID,
    ) -> Result<jlong> {
        let value = unsafe {
            (**env.get_raw()).GetLongField.unwrap()(
                env.get_raw(),
                obj.as_raw(),
                field_id.into_raw(),
            )
        };

        if env.exception_check()? {
            Err(Error::JavaException)
        } else {
            Ok(value)
        }
    }

    unsafe fn get_rust_field<'a, 'other_local, O, S, T>(
        env: &JNIEnv<'a>,
        obj: O,
        field: S,
    ) -> Result<MutexGuard<'a, T>>
    where
        O: AsRef<JObject<'other_local>>,
        S: Into<JNIString>,
        T: Send + 'static,
    {
        let obj = obj.as_ref();
        let class = env.get_object_class(obj)?;
        let field_id = Self::get_jlong_field_id(env, &class, field)?;

        let value = {
            let _guard = env.lock_obj(obj)?;
            Self::get_jlong_field(env, obj, &field_id)?
        };

        let ptr = ptr::NonNull::new(value as usize as *mut Mutex<T>)
            .ok_or_else(|| Error::NullPtr(""))?;

        Ok(ptr.as_ref().lock().unwrap())
    }

    fn native_data<'a>(
        env: &JNIEnv<'a>,
        obj: &JObject<'a>,
    ) -> Result<MutexGuard<'a, Box<dyn SomeOtherType>>> {
        unsafe { Self::get_rust_field(env, obj, "nativeData") }
    }
}
```

**Comment by rib** [comment]
The sketch out above looked reasonable but hopefully you don't mind that I went ahead and opened up a PR to implement this in terms of using `unsafe_clone()` to not need to change too much about the implementation.

I've also tried to improve the documentation of the safety issues and also tried to avoid a bit of duplication between the get/set/take functions.

It'd be good to get your feedback on https://github.com/jni-rs/jni-rs/pull/458 to hear if you think that could work for you.

I do actually like that your code above is simpler in many ways with less abstraction.

I'm not a big fan of the `Desc` trait in the `jni` API in particular which I feel hides a bit to much magic for my tastes.

I'm also not a big fan of how the `jni` API wraps over primitive and reference values with types like `JValueOwned` so we end up with apis like `get_field` or `get_field_unchecked` that look like they might create local references (since the need to borrow the env mutably) but they don't if they are handling primitive types.

**Comment by rib** [comment]
Related to this I also opened:
- https://github.com/jni-rs/jni-rs/pull/456
- https://github.com/jni-rs/jni-rs/pull/457

**Comment by koutheir** [comment]
> The sketch out above looked reasonable but hopefully you don't mind that I went ahead and opened up a PR to implement this in terms of using unsafe_clone() to not need to change too much about the implementation.

Sure.

> I've also tried to improve the documentation of the safety issues and also tried to avoid a bit of duplication between the get/set/take functions.

Yeah, `lock_rust_field` looks like a good idea.

> It'd be good to get your feedback on https://github.com/jni-rs/jni-rs/pull/458 to hear if you think that could work for you.

I think it's a reasonable solution, to keep using the same abstractions.

> I'm not a big fan of the Desc trait in the jni API in particular which I feel hides a bit to much magic for my tastes.
>
> I'm also not a big fan of how the jni API wraps over primitive and reference values with types like JValueOwned so we end up with apis like get_field or get_field_unchecked that look like they might create local references (since the need to borrow the env mutably) but they don't if they are handling primitive types.

I agree, and that's the reason that, at some point, I dropped it in my sketch. It's too pessimistic, assuming that we might create references, even though in many cases (e.g., primitive types) no references would be visible to the caller. It's a common denominator that is too broad and too conservative, thus the exclusive reference to `JNIEnv`.

**Comment by argv-minus-one** [comment]
@rib: Yes, `get_object_class` should require `&mut self` for that reason. I must have overlooked it—sorry about that.
