### ISSUE TITLE
ReleaseByteArrayElements or any other way to deallocate the arrays

### ISSUE THREAD

**Issue by r3bb1t** [jni-rs/jni-rs#482]
We need to add support for similar functions for deallocating arrays.

The fuctions mentioned in documentation are not accessible from my code: https://docs.rs/jni/latest/jni/sys/struct.JNINativeInterface_.html#structfield.ReleaseByteArrayElements

I'm running my code in a **loop** and don't want to wait for garbage collector to collect lots of my unused local refs, because there are thousands of them being generated each sec. Calling the **delete_local_ref** method of **JNIEnv** is not an option, it leads to errors with allocating memory.

<details> 
<summary> Screenshot </summary>
<img src="https://github.com/jni-rs/jni-rs/assets/49586603/fdc14d8c-6a25-4708-8625-4d3c36072fd3">
</details>

**Comment by r3bb1t** [comment]
Updated: It seems that the memory allocation problems are still present even without **delete_local_ref**

**Comment by r3bb1t** [comment]
> `ReleaseByteArrayElements` is called immediately when a `jni::objects::AutoElements` or `jni::objects::AutoElementsCritical` is dropped.

I didn't think about this option tho, but there is a problem with it. The method **new()** is visible only within its crate's scope, so i can't create one. I think it should become public as well as providing an example of the **new()** invocation.

Right now it's defined as 
```rust
pub(crate) fn new(
```

**Comment by r3bb1t** [comment]
> Could you show me the source code for your loop? Maybe I can spot a leak.


```rust
pub fn testing_main_with_jni_leak(
    afl_input: &[u8],
    jvm: &JavaVM,
    opts: &Opts,
) -> jni::errors::Result<()> {
    let afl_input_as_str;

    if let Ok(input) = str::from_utf8(afl_input) {
        afl_input_as_str = input;
    } else {
        return Ok(());
    }
    let argv: Vec<String> = opts.argv.clone().unwrap();

    let env = &mut jvm.attach_current_thread()?;

    let empty_string = AutoLocal::new(env.new_string("")?, &env);

    let array_of_strings = AutoLocal::new(
        env.new_object_array(argv.len() as i32, "java/lang/String", empty_string)?,
        &env,
    );

    for (i, arg) in argv.iter().enumerate() {
        let input_string = if arg == "@@" {
            AutoLocal::new(env.new_string(afl_input_as_str)?, &env)
        } else {
            AutoLocal::new(env.new_string(arg)?, &env)
        };
        env.set_object_array_element(&array_of_strings, i as i32, input_string)?;
    }

    env.call_static_method(
        "FuzzException",
        "main",
        VOID_MAIN_DESCRIPTOR,
        &[JValue::Object(&array_of_strings)],
    )?;

    Ok(())
}
```

Here i am creating the new **String[]** array with the size of **argv** vector. If one of the supplied strings equals "@@", i replace it with the input data from **afl_input** variable (assume that **afl_input** always holds unique data every time). 
After a few seconds, my program crash because it can't allocate memory (as shown on screenshot before).

**Comment by r3bb1t** [comment]
I believe that the error happens with **empty_string** variable. If i don't try to delete its local ref i'm not facing the crashes. 
But i need to delete it's local reference, because there are still too much of them are being generated in my loop.

I also tried not wrapping it into **AutoLocal** and deleting it with:

```rust
env.delete_local_ref(empty_string)?;
```
Still no luck, same problem

**Comment by argv-minus-one** [comment]
Well, your code looks correct.

By 400k+ iterations, I assume you mean this `testing_main_with_jni_leak` function is being called that many times, as part of a fuzz test?

If so, then I wonder if `JavaVM::attach_current_thread` is the culprit. Attaching a thread to the JVM is a costly and complicated operation, and I don't think the HotSpot JVM developers intended for it to happen more than once per thread, so it may very well be that the JVM itself is leaking memory (or, at least, not deallocating it soon enough).

Can you ensure that it only gets called once? If not, try using `JavaVM::attach_current_thread_permanently` or `JavaVM::attach_current_thread_as_daemon` instead, which will attach the thread if it isn't already attached, and never detach it.

Please tell me if that helps! If it does, I need to add a warning to this crate's documentation.

**Comment by r3bb1t** [comment]
When i replaced **attach_current_thread** with **attach_current_thread_as_daemon** it took my fuzzer a bit more time to crash. 
Still no luck here.

You can find my fuzzer here and possibly spot a bug: https://github.com/r3bb1t/jFuzz/tree/93717b9677d7b853fdddc15dd376edda810f4da3
 I assume that the error is maybe on the jni bindings side.

Try this to reproduce the error:
* git clone
* Edit the function **testing_main_with_jni_leak** in JavaFuzz/src/java_harness.rs as shown in this issue.
* cd JavaFuzz
* cargo run --release examples/fuzz_exception/fuzz_exception.yml

**Comment by argv-minus-one** [comment]
I got your program working, wrapped most of `testing_main_with_jni_leak` in a call to `JNIEnv::with_local_frame` to delete the local references, and got the same allocation error as you did.

After much bewilderment, I noticed that libafl's `fork` feature flag is enabled. I turned it off in `Cargo.toml`:

```
[dependencies]
libafl = { version = "0.10.1", default-features = false, features = ["std", "derive", "llmp_compression", "llmp_small_maps", "llmp_broker_timeouts", "rand_trait", "prelude", "gzip", "regex", "tui"] }
```

(Notice that I've listed every default feature *except* `fork`.)

After doing this, your program seems to be working correctly:

```
[Stats #1] run time: 0h-4m-29s, clients: 2, corpus: 6, objectives: 1, executions: 1296520, exec/sec: 4.816k
[Testcase #1] run time: 0h-4m-29s, clients: 2, corpus: 7, objectives: 1, executions: 1296524, exec/sec: 4.816k
```

So, the problem must be that the fuzzer was calling the `fork` system call. I see that [you had commented out the use of `InProcessForkExecutor` and are using a different executor instead](https://github.com/r3bb1t/jFuzz/blob/93717b9677d7b853fdddc15dd376edda810f4da3/JavaFuzz/src/fuzzer2.rs#L202), but apparently that different executor will still `fork` if the feature flag is enabled.

You probably know this already, but calling `fork` in a multithreaded process, including any process containing a running JVM, will cause massive breakage, because only the *current* thread is copied to the child process. As far as the program is concerned, all other threads have suddenly disappeared, including the JVM garbage collector thread!

Side note to anyone reading this thread: to get @r3bb1t's project running, you need to do a couple more things:

* Copy `JavaFuzz/java_instrumentator/src/natif/upd.class` to `JavaFuzz/java_instrumentator/build/natif/upd.class`.
* Manually build `JavaFuzz/examples/fuzz_sigsegv/build/{libmain.so,Test.class}` according to the instructions in [`xtask/src/main.rs`](https://github.com/r3bb1t/jFuzz/blob/93717b9677d7b853fdddc15dd376edda810f4da3/xtask/src/main.rs#L44). For some reason, actually running this program panics with `An error occured while compiling the example: Os { code: 2, kind: NotFound, message: "No such file or directory" }` at xtask/src/main.rs:18:32.

**Comment by r3bb1t** [comment]
Thank you, it really helped. 

I've managed to get my fuzzer work for one and half an hour and making 23 million executions without crashing. (Eventually it crashed some time later, but i think it was not due to jni).

You really helped me a lot and saved a ton of time. 

Again, thank you for your time and effort. Your help is going to be mentioned when the MVP release will be ready.

I think we can close the issue
