### ISSUE TITLE
How can I return an int array in a JNI call?

### ISSUE THREAD

**Issue by ShenFeng312** [jni-rs/jni-rs#492]
I have tried using the following code, but it keeps throwing errors.

```RUST
pub unsafe extern "C" fn method_name
(env: JNIEnv, _class: JClass) -> jintArray {
 
    let  array = env.new_int_array(10).unwrap();
    ...........
   env.set_int_array_region(&array,0,somebuffer);
   array
}
```

**Comment by ShenFeng312** [comment]
What can I do?

**Comment by argv-minus-one** [comment]
Which errors do you get, and at which line of code?

**Comment by ShenFeng312** [comment]
> Which errors do you get, and at which line of code?
```
75  | (env: JNIEnv, _class: JClass) -> jintArray {
    |                                  --------- expected `*mut _jobject` because of return type
...
109 |     array
    |     ^^^^^ expected `*mut _jobject`, found `JPrimitiveArray<'_, i32>`
```
I dont know how to fix it

**Comment by ShenFeng312** [comment]
I tried using the following code. It compiles successfully, but when I call it in Java, I encounter the following error: `free(): invalid pointer.` It seems like the reference to the array has become invalid. However, when I tested it in Rust, everything worked fine except for the last JNI-related call. What can I do to test it further?@argv-minus-one

**Comment by argv-minus-one** [comment]
Sorry! I seem to have missed that you replied here. Didn't mean to ignore you like that.

I need to see more of your code. The code you've listed so far looks sound, so you must have omitted whatever is causing the problem.

I will say that your `extern fn` should *not* be `unsafe`. Something in the function is causing undefined behavior, and because the function is marked `unsafe`, you aren't getting any compile errors about it.
