### ISSUE TITLE
JObject should implement Copy and/or Clone

### ISSUE THREAD

**Issue by Megadash452** [jni-rs/jni-rs#540]
JObject not implementing Clone makes it harder to use in structs because you'd either have to store a reference and add a lifetime for each JObject you store, or store the owned JObject, but use `JObject::from_raw` every time the JObject is passed, which requires unsafe code and opens the possibility of changing the lifetime to an invalid one.

Needs a lifetime for every JObject stored:
```rust
struct Thing<'local, 'o1, 'o2>{
    object1: &'o1 JObject<'local>,
    object2: &'o2 JObject<'local>,
}
```
Using `JObject::from_raw()` requires unsafe code:
```rust
struct Thing<'local>(JObject<'local>);

let thing1 = Thing(unsafe { JObject::from_raw(object.clone()) });
let thing2 = Thing(unsafe { JObject::from_raw(object.clone()) });
```

Since JObject is just a pointer with a lifetime (aka a reference) it should implement Copy (or at least Clone).

**Comment by argv-minus-one** [comment]
If `JObject` implemented `Copy`, then it would be possible to cause a use-after-free or double-free without `unsafe`, by deleting both the original and the copy with `JNIEnv::delete_local_ref`.

It is not possible to implement `Clone` for `JObject` because cloning it can fail and requires a `&JNIEnv`.

To duplicate a `JObject`, use `JNIEnv::new_local_ref`.

**Comment by Megadash452** [comment]
Yeah that works, thanks. Sorry for wasting your time.
