### ISSUE TITLE
More descriptive errors for InvalidArgList

### ISSUE THREAD

**Issue by zeekruz** [jni-rs/jni-rs#86]
Method with void signature ()V doesn't work:

Rust:
call_method(callback_object, "onStarted", "()V", &[JValue::Void]).unwrap()

Java:
public void onStarted();

**Comment by fpoli** [comment]
Have you tried the following?
```rust
call_method(callback_object, "onStarted", "()V", &[]).unwrap()
```

**Comment by zeekruz** [comment]
Yes. It definitelly works. Thanks! However I think it would be nice if parser skips the args in case of void signature.

**Comment by dmitry-timofeev** [comment]
I don't think that's a better behaviour because it hides a programming error (= a user is expected to pass as many arguments as the Java method accepts). But if there is an error, I'd expect a meaningful error describing what is wrong. It seems the library already handles this case: https://github.com/prevoty/jni-rs/blob/aac22fddf6b2c3a578b4d27385d9dfc10f984a4b/src/wrapper/jnienv.rs#L833 

Did you get a descriptive error message?

**Comment by dmitry-timofeev** [comment]
Probably `InvalidArgList` error shall be expanded with information about expected signature and actual number of passed parameters and their types, similarly to `FieldNotFound`:

https://github.com/prevoty/jni-rs/blob/8592176cd21c9fa70a3788140243096a4c753924/src/wrapper/errors.rs#L27

**Comment by zeekruz** [comment]
Did you get a descriptive error message?
-- No.

I don't think that's a better behaviour because it hides a programming error
-- Agree.

Probably InvalidArgList error shall be expanded with information about expected signature 
-- This is the best solution!
